
package principal;


import Controlador.CtrlProgramacion;
import Controlador.CtrlTecnicos;
import Controlador.CtrlUsuarios;
import Modelo.ConsultaEmpleados;
import Modelo.ConsultaUsuarios;
import java.awt.Color;
import java.awt.Image;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import paneles.CambiaPanel;
import paneles.pnlAutorizacion;
import paneles.Caja_menor;
import paneles.pnlListaTecnicos;
import paneles.pnlProgramacion;
import paneles.pnlSettings;
import paneles.pnlUsuarios;



public class Principal extends javax.swing.JFrame {

    int x, y;
    String cargo = null;
    
    public Principal(String nombre, String id_usuario, String cargo) {
        initComponents();
        this.cargo = cargo;
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/laptop.png"));
        setIconImage(icon);
        setTitle("Sistemas Palacios - Gestión de viáticos");
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(this);
        this.uno.setSelected(true);
        lblUsuario.setText(nombre.toUpperCase());
        txtId.setText(id_usuario);
        txtId.setVisible(false);
        new CambiaPanel(pnlPrincipal, new paneles.pnlHome());
    }
    
    public Principal() {
        initComponents();
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/laptop.png"));
        setIconImage(icon);
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(this);
        this.uno.setSelected(true);
        
        new CambiaPanel(pnlPrincipal, new paneles.pnlHome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        uno = new rsbuttom.RSButtonMetro();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tres = new rsbuttom.RSButtonMetro();
        dos = new rsbuttom.RSButtonMetro();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cuatro = new rsbuttom.RSButtonMetro();
        ocho = new rsbuttom.RSButtonMetro();
        siete = new rsbuttom.RSButtonMetro();
        seis = new rsbuttom.RSButtonMetro();
        cinco = new rsbuttom.RSButtonMetro();
        txtId = new javax.swing.JTextField();
        lblUsuario = new javax.swing.JLabel();
        nueve = new rsbuttom.RSButtonMetro();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnlCentro = new javax.swing.JPanel();
        pnlBarraMenu = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        pnlMenu.setBackground(new java.awt.Color(239, 238, 244));
        pnlMenu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 0, new java.awt.Color(239, 238, 244)));

        uno.setForeground(new java.awt.Color(128, 128, 131));
        uno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/casa.png"))); // NOI18N
        uno.setText("Inicio");
        uno.setColorHover(new java.awt.Color(204, 204, 204));
        uno.setColorNormal(new java.awt.Color(204, 204, 204));
        uno.setColorPressed(new java.awt.Color(204, 204, 204));
        uno.setColorTextHover(new java.awt.Color(128, 128, 131));
        uno.setColorTextNormal(new java.awt.Color(128, 128, 131));
        uno.setColorTextPressed(new java.awt.Color(128, 128, 131));
        uno.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        uno.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        uno.setIconTextGap(25);
        uno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                unoMousePressed(evt);
            }
        });
        uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unoActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(239, 238, 244));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(128, 128, 131));
        jLabel1.setText("OPCIONES DE MENÚ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tres.setBackground(new java.awt.Color(239, 238, 244));
        tres.setForeground(new java.awt.Color(128, 128, 131));
        tres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pagar.png"))); // NOI18N
        tres.setText("Viaticos");
        tres.setColorHover(new java.awt.Color(204, 204, 204));
        tres.setColorNormal(new java.awt.Color(239, 238, 244));
        tres.setColorPressed(new java.awt.Color(204, 204, 204));
        tres.setColorTextHover(new java.awt.Color(128, 128, 131));
        tres.setColorTextNormal(new java.awt.Color(128, 128, 131));
        tres.setColorTextPressed(new java.awt.Color(128, 128, 131));
        tres.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tres.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        tres.setIconTextGap(25);
        tres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tresMousePressed(evt);
            }
        });
        tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresActionPerformed(evt);
            }
        });

        dos.setBackground(new java.awt.Color(239, 238, 244));
        dos.setForeground(new java.awt.Color(128, 128, 131));
        dos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/calendario.png"))); // NOI18N
        dos.setText("Programaciones");
        dos.setColorHover(new java.awt.Color(204, 204, 204));
        dos.setColorNormal(new java.awt.Color(239, 238, 244));
        dos.setColorPressed(new java.awt.Color(204, 204, 204));
        dos.setColorTextHover(new java.awt.Color(128, 128, 131));
        dos.setColorTextNormal(new java.awt.Color(128, 128, 131));
        dos.setColorTextPressed(new java.awt.Color(128, 128, 131));
        dos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        dos.setIconTextGap(25);
        dos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dosMousePressed(evt);
            }
        });
        dos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(239, 238, 244));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(128, 128, 131));
        jLabel3.setText("ADMINISTRADOR");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        cuatro.setBackground(new java.awt.Color(239, 238, 244));
        cuatro.setForeground(new java.awt.Color(128, 128, 131));
        cuatro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reportes.png"))); // NOI18N
        cuatro.setText("Reportes");
        cuatro.setColorHover(new java.awt.Color(204, 204, 204));
        cuatro.setColorNormal(new java.awt.Color(239, 238, 244));
        cuatro.setColorPressed(new java.awt.Color(204, 204, 204));
        cuatro.setColorTextHover(new java.awt.Color(128, 128, 131));
        cuatro.setColorTextNormal(new java.awt.Color(128, 128, 131));
        cuatro.setColorTextPressed(new java.awt.Color(128, 128, 131));
        cuatro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cuatro.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        cuatro.setIconTextGap(25);
        cuatro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cuatroMousePressed(evt);
            }
        });
        cuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuatroActionPerformed(evt);
            }
        });

        ocho.setBackground(new java.awt.Color(239, 238, 244));
        ocho.setForeground(new java.awt.Color(128, 128, 131));
        ocho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ajustes.png"))); // NOI18N
        ocho.setText("Ajustes");
        ocho.setColorHover(new java.awt.Color(204, 204, 204));
        ocho.setColorNormal(new java.awt.Color(239, 238, 244));
        ocho.setColorPressed(new java.awt.Color(204, 204, 204));
        ocho.setColorTextHover(new java.awt.Color(128, 128, 131));
        ocho.setColorTextNormal(new java.awt.Color(128, 128, 131));
        ocho.setColorTextPressed(new java.awt.Color(128, 128, 131));
        ocho.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ocho.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ocho.setIconTextGap(25);
        ocho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ochoMousePressed(evt);
            }
        });
        ocho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ochoActionPerformed(evt);
            }
        });

        siete.setBackground(new java.awt.Color(239, 238, 244));
        siete.setForeground(new java.awt.Color(128, 128, 131));
        siete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/jefe.png"))); // NOI18N
        siete.setText("Usuarios");
        siete.setColorHover(new java.awt.Color(204, 204, 204));
        siete.setColorNormal(new java.awt.Color(239, 238, 244));
        siete.setColorPressed(new java.awt.Color(204, 204, 204));
        siete.setColorTextHover(new java.awt.Color(128, 128, 131));
        siete.setColorTextNormal(new java.awt.Color(128, 128, 131));
        siete.setColorTextPressed(new java.awt.Color(128, 128, 131));
        siete.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        siete.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        siete.setIconTextGap(25);
        siete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sieteMousePressed(evt);
            }
        });
        siete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sieteActionPerformed(evt);
            }
        });

        seis.setBackground(new java.awt.Color(239, 238, 244));
        seis.setForeground(new java.awt.Color(128, 128, 131));
        seis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/team.png"))); // NOI18N
        seis.setText("Empleados");
        seis.setColorHover(new java.awt.Color(204, 204, 204));
        seis.setColorNormal(new java.awt.Color(239, 238, 244));
        seis.setColorPressed(new java.awt.Color(204, 204, 204));
        seis.setColorTextHover(new java.awt.Color(128, 128, 131));
        seis.setColorTextNormal(new java.awt.Color(128, 128, 131));
        seis.setColorTextPressed(new java.awt.Color(128, 128, 131));
        seis.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        seis.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        seis.setIconTextGap(25);
        seis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                seisMousePressed(evt);
            }
        });
        seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seisActionPerformed(evt);
            }
        });

        cinco.setBackground(new java.awt.Color(239, 238, 244));
        cinco.setForeground(new java.awt.Color(128, 128, 131));
        cinco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/autorizacion.png"))); // NOI18N
        cinco.setText("Autorizaciones");
        cinco.setColorHover(new java.awt.Color(204, 204, 204));
        cinco.setColorNormal(new java.awt.Color(239, 238, 244));
        cinco.setColorPressed(new java.awt.Color(204, 204, 204));
        cinco.setColorTextHover(new java.awt.Color(128, 128, 131));
        cinco.setColorTextNormal(new java.awt.Color(128, 128, 131));
        cinco.setColorTextPressed(new java.awt.Color(128, 128, 131));
        cinco.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cinco.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        cinco.setIconTextGap(25);
        cinco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cincoMousePressed(evt);
            }
        });
        cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cincoActionPerformed(evt);
            }
        });

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(102, 102, 102));
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuario.setText("Usuario");
        lblUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUsuarioMouseClicked(evt);
            }
        });

        nueve.setBackground(new java.awt.Color(239, 238, 244));
        nueve.setForeground(new java.awt.Color(128, 128, 131));
        nueve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgsp/contabilidad.png"))); // NOI18N
        nueve.setText("Caja Menor");
        nueve.setColorHover(new java.awt.Color(204, 204, 204));
        nueve.setColorNormal(new java.awt.Color(239, 238, 244));
        nueve.setColorPressed(new java.awt.Color(204, 204, 204));
        nueve.setColorTextHover(new java.awt.Color(128, 128, 131));
        nueve.setColorTextNormal(new java.awt.Color(128, 128, 131));
        nueve.setColorTextPressed(new java.awt.Color(128, 128, 131));
        nueve.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nueve.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        nueve.setIconTextGap(25);
        nueve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nueveMousePressed(evt);
            }
        });
        nueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nueveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ocho, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(siete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(seis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cinco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cuatro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tres, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nueve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 10, Short.MAX_VALUE))
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(uno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(uno, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(dos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tres, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(seis, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(siete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nueve, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsuario)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 8.3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 1);
        jPanel1.add(pnlMenu, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sistemas Palacios Ltda");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgsp/antena_1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(977, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 0.2;
        jPanel1.add(jPanel2, gridBagConstraints);

        pnlCentro.setBackground(new java.awt.Color(255, 255, 255));

        pnlBarraMenu.setBackground(new java.awt.Color(255, 255, 255));
        pnlBarraMenu.setLayout(new javax.swing.BoxLayout(pnlBarraMenu, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane1.setBorder(null);

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setLayout(new javax.swing.BoxLayout(pnlPrincipal, javax.swing.BoxLayout.LINE_AXIS));
        jScrollPane1.setViewportView(pnlPrincipal);

        javax.swing.GroupLayout pnlCentroLayout = new javax.swing.GroupLayout(pnlCentro);
        pnlCentro.setLayout(pnlCentroLayout);
        pnlCentroLayout.setHorizontalGroup(
            pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBarraMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        pnlCentroLayout.setVerticalGroup(
            pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCentroLayout.createSequentialGroup()
                .addComponent(pnlBarraMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.weighty = 0.1;
        jPanel1.add(pnlCentro, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void unoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unoActionPerformed
        new CambiaPanel(pnlPrincipal, new paneles.pnlHome());
        new CambiaPanel(pnlBarraMenu, new paneles.pnlMenuVacio());
        if(this.uno.isSelected()){
            this.uno.setColorNormal(new Color(204,204,204));
            this.uno.setColorHover(new Color(204,204,204));
            this.uno.setColorPressed(new Color(204,204,204));
            
            this.dos.setColorNormal(new Color(239,238,244));
            this.dos.setColorHover(new Color(204,204,204));
            this.dos.setColorPressed(new Color(204,204,204));
            
            this.tres.setColorNormal(new Color(239,238,244));
            this.tres.setColorHover(new Color(204,204,204));
            this.tres.setColorPressed(new Color(204,204,204));
            
            this.cuatro.setColorNormal(new Color(239,238,244));
            this.cuatro.setColorHover(new Color(204,204,204));
            this.cuatro.setColorPressed(new Color(204,204,204));
          
            this.cinco.setColorNormal(new Color(239,238,244));
            this.cinco.setColorHover(new Color(204,204,204));
            this.cinco.setColorPressed(new Color(204,204,204));
            
            this.seis.setColorNormal(new Color(239,238,244));
            this.seis.setColorHover(new Color(204,204,204));
            this.seis.setColorPressed(new Color(204,204,204));
            
            this.siete.setColorNormal(new Color(239,238,244));
            this.siete.setColorHover(new Color(204,204,204));
            this.siete.setColorPressed(new Color(204,204,204));
            
            this.ocho.setColorNormal(new Color(239,238,244));
            this.ocho.setColorHover(new Color(204,204,204));
            this.ocho.setColorPressed(new Color(204,204,204));
        }else{
            this.uno.setColorNormal(new Color(239,238,244));
            this.uno.setColorHover(new Color(204,204,204));
            this.uno.setColorPressed(new Color(204,204,204));
        }
    }//GEN-LAST:event_unoActionPerformed

    private void unoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unoMousePressed
        this.uno.setSelected(true);
        this.dos.setSelected(false);
        this.tres.setSelected(false);
        this.cuatro.setSelected(false);
        this.cinco.setSelected(false);
        this.seis.setSelected(false);
        this.siete.setSelected(false);
        this.ocho.setSelected(false);
    }//GEN-LAST:event_unoMousePressed

    private void tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresActionPerformed
        CtrlUsuarios ctrl = new CtrlUsuarios();
        if(ctrl.validarUsuarioModulo(txtId.getText(), "2")){
            new CambiaPanel(pnlPrincipal, new paneles.pnlViatico());
            new CambiaPanel(pnlBarraMenu, new paneles.menu_viaticos(txtId.getText()));
            if(this.tres.isSelected()){
                this.tres.setColorNormal(new Color(204,204,204));
                this.tres.setColorHover(new Color(204,204,204));
                this.tres.setColorPressed(new Color(204,204,204));

                this.uno.setColorNormal(new Color(239,238,244));
                this.uno.setColorHover(new Color(204,204,204));
                this.uno.setColorPressed(new Color(204,204,204));

                this.dos.setColorNormal(new Color(239,238,244));
                this.dos.setColorHover(new Color(204,204,204));
                this.dos.setColorPressed(new Color(204,204,204));

                this.cuatro.setColorNormal(new Color(239,238,244));
                this.cuatro.setColorHover(new Color(204,204,204));
                this.cuatro.setColorPressed(new Color(204,204,204));
            
                this.cinco.setColorNormal(new Color(239,238,244));
                this.cinco.setColorHover(new Color(204,204,204));
                this.cinco.setColorPressed(new Color(204,204,204));

                this.seis.setColorNormal(new Color(239,238,244));
                this.seis.setColorHover(new Color(204,204,204));
                this.seis.setColorPressed(new Color(204,204,204));

                this.siete.setColorNormal(new Color(239,238,244));
                this.siete.setColorHover(new Color(204,204,204));
                this.siete.setColorPressed(new Color(204,204,204));

                this.ocho.setColorNormal(new Color(239,238,244));
                this.ocho.setColorHover(new Color(204,204,204));
                this.ocho.setColorPressed(new Color(204,204,204));
            }else{
                this.tres.setColorNormal(new Color(239,238,244));
                this.tres.setColorHover(new Color(204,204,204));
                this.tres.setColorPressed(new Color(204,204,204));
            }
        }else {
            JOptionPane.showMessageDialog(null, "No tiene permisos para acceder \na este módulo");
        }
    }//GEN-LAST:event_tresActionPerformed

    private void tresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tresMousePressed
        this.uno.setSelected(false);
        this.dos.setSelected(false);
        this.tres.setSelected(true);
        this.cuatro.setSelected(false);
        this.cinco.setSelected(false);
        this.seis.setSelected(false);
        this.siete.setSelected(false);
        this.ocho.setSelected(false);
    }//GEN-LAST:event_tresMousePressed
           
    private void dosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dosMousePressed
        this.uno.setSelected(false);
        this.dos.setSelected(true);
        this.tres.setSelected(false);
        this.cuatro.setSelected(false);
        this.cinco.setSelected(false);
        this.seis.setSelected(false);
        this.siete.setSelected(false);
        this.ocho.setSelected(false);
    }//GEN-LAST:event_dosMousePressed

    
    
    private void dosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosActionPerformed
        CtrlUsuarios ctrl = new CtrlUsuarios();
        if(ctrl.validarUsuarioModulo(txtId.getText(), "1")){
            String id_usuario = txtId.getText();
            pnlProgramacion r = new pnlProgramacion();
            ConsultaEmpleados mod = new ConsultaEmpleados();
            CtrlProgramacion control = new CtrlProgramacion(r, mod, id_usuario, this.cargo);
            new CambiaPanel(pnlPrincipal, r);
            new CambiaPanel(pnlBarraMenu, new paneles.pnlMenuVacio()); 
            if(this.dos.isSelected()){
                this.dos.setColorNormal(new Color(204,204,204));
                this.dos.setColorHover(new Color(204,204,204));
                this.dos.setColorPressed(new Color(204,204,204));

                this.uno.setColorNormal(new Color(239,238,244));
                this.uno.setColorHover(new Color(204,204,204));
                this.uno.setColorPressed(new Color(204,204,204));

                this.tres.setColorNormal(new Color(239,238,244));
                this.tres.setColorHover(new Color(204,204,204));
                this.tres.setColorPressed(new Color(204,204,204));

                this.cuatro.setColorNormal(new Color(239,238,244));
                this.cuatro.setColorHover(new Color(204,204,204));
                this.cuatro.setColorPressed(new Color(204,204,204));
                
                this.cinco.setColorNormal(new Color(239,238,244));
                this.cinco.setColorHover(new Color(204,204,204));
                this.cinco.setColorPressed(new Color(204,204,204));

                this.seis.setColorNormal(new Color(239,238,244));
                this.seis.setColorHover(new Color(204,204,204));
                this.seis.setColorPressed(new Color(204,204,204));

                this.siete.setColorNormal(new Color(239,238,244));
                this.siete.setColorHover(new Color(204,204,204));
                this.siete.setColorPressed(new Color(204,204,204));

                this.ocho.setColorNormal(new Color(239,238,244));
                this.ocho.setColorHover(new Color(204,204,204));
                this.ocho.setColorPressed(new Color(204,204,204));
            }else{
                this.dos.setColorNormal(new Color(239,238,244));
                this.dos.setColorHover(new Color(204,204,204));
                this.dos.setColorPressed(new Color(204,204,204));
            }
        }else {
            JOptionPane.showMessageDialog(null, "No tiene permisos para acceder a \neste módulo");
        }
    }//GEN-LAST:event_dosActionPerformed

    private void cuatroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuatroMousePressed
        this.uno.setSelected(false);
        this.dos.setSelected(false);
        this.tres.setSelected(false);
        this.cuatro.setSelected(true);
        this.cinco.setSelected(false);
        this.seis.setSelected(false);
        this.siete.setSelected(false);
        this.ocho.setSelected(false);
    }//GEN-LAST:event_cuatroMousePressed

    private void cuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuatroActionPerformed
        CtrlUsuarios ctrl = new CtrlUsuarios();
        if(ctrl.validarUsuarioModulo(txtId.getText(), "3")){
            new CambiaPanel(pnlPrincipal, new paneles.pnlReportes());
            new CambiaPanel(pnlBarraMenu, new paneles.pnlMenuVacio()); 
            if(this.cuatro.isSelected()){
                this.uno.setColorNormal(new Color(239,238,244));
                this.uno.setColorHover(new Color(204,204,204));
                this.uno.setColorPressed(new Color(204,204,204));

                this.dos.setColorNormal(new Color(239,238,244));
                this.dos.setColorHover(new Color(204,204,204));
                this.dos.setColorPressed(new Color(204,204,204));

                this.tres.setColorNormal(new Color(239,238,244));
                this.tres.setColorHover(new Color(204,204,204));
                this.tres.setColorPressed(new Color(204,204,204));

                this.cuatro.setColorNormal(new Color(204,204,204));
                this.cuatro.setColorHover(new Color(204,204,204));
                this.cuatro.setColorPressed(new Color(204,204,204));

                this.cinco.setColorNormal(new Color(239,238,244));
                this.cinco.setColorHover(new Color(204,204,204));
                this.cinco.setColorPressed(new Color(204,204,204));

                this.seis.setColorNormal(new Color(239,238,244));
                this.seis.setColorHover(new Color(204,204,204));
                this.seis.setColorPressed(new Color(204,204,204));

                this.siete.setColorNormal(new Color(239,238,244));
                this.siete.setColorHover(new Color(204,204,204));
                this.siete.setColorPressed(new Color(204,204,204));

                this.ocho.setColorNormal(new Color(239,238,244));
                this.ocho.setColorHover(new Color(204,204,204));
                this.ocho.setColorPressed(new Color(204,204,204));
            }else{
                this.cuatro.setColorNormal(new Color(239,238,244));
                this.cuatro.setColorHover(new Color(204,204,204));
                this.cuatro.setColorPressed(new Color(204,204,204));
            }
        }else {
            JOptionPane.showMessageDialog(null, "No tiene permisos para acceder a \neste módulo");
        }
    }//GEN-LAST:event_cuatroActionPerformed

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        Point mueve = MouseInfo.getPointerInfo().getLocation();
        this.setLocation(mueve.x - x, mueve.y - y);
    }//GEN-LAST:event_jPanel2MouseDragged

    
    private void ochoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ochoMousePressed
        this.uno.setSelected(false);
        this.dos.setSelected(false);
        this.tres.setSelected(false);
//        this.cuatro.setSelected(false);
        this.cinco.setSelected(false);
        this.seis.setSelected(false);
        this.siete.setSelected(false);
        this.ocho.setSelected(true);
    }//GEN-LAST:event_ochoMousePressed

    private void ochoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ochoActionPerformed
        CtrlUsuarios ctrl = new CtrlUsuarios();
        if(ctrl.validarUsuarioModulo(txtId.getText(), "7")){
            pnlSettings mun = new pnlSettings();
            new CambiaPanel(pnlPrincipal, mun);        
            new CambiaPanel(pnlBarraMenu, new paneles.pnlMenuVacio());
            //CtrlMunicipios ctrl = new CtrlMunicipios();
            if(this.ocho.isSelected()){
                this.uno.setColorNormal(new Color(239,238,244));
                this.uno.setColorHover(new Color(204,204,204));
                this.uno.setColorPressed(new Color(204,204,204));

                this.dos.setColorNormal(new Color(239,238,244));
                this.dos.setColorHover(new Color(204,204,204));
                this.dos.setColorPressed(new Color(204,204,204));

                this.tres.setColorNormal(new Color(239,238,244));
                this.tres.setColorHover(new Color(204,204,204));
                this.tres.setColorPressed(new Color(204,204,204));

                this.cuatro.setColorNormal(new Color(239,238,244));
                this.cuatro.setColorHover(new Color(204,204,204));
                this.cuatro.setColorPressed(new Color(204,204,204));
                
                this.cinco.setColorNormal(new Color(239,238,244));
                this.cinco.setColorHover(new Color(204,204,204));
                this.cinco.setColorPressed(new Color(204,204,204));

                this.seis.setColorNormal(new Color(239,238,244));
                this.seis.setColorHover(new Color(204,204,204));
                this.seis.setColorPressed(new Color(204,204,204));

                this.siete.setColorNormal(new Color(239,238,244));
                this.siete.setColorHover(new Color(204,204,204));
                this.siete.setColorPressed(new Color(204,204,204));

                this.ocho.setColorNormal(new Color(204,204,204));
                this.ocho.setColorHover(new Color(204,204,204));
                this.ocho.setColorPressed(new Color(204,204,204));
            }else{
                this.ocho.setColorNormal(new Color(239,238,244));
                this.ocho.setColorHover(new Color(204,204,204));
                this.ocho.setColorPressed(new Color(204,204,204));
            }
        }else {
            JOptionPane.showMessageDialog(null, "No tiene permisos para acceder a \neste módulo");
        }
    }//GEN-LAST:event_ochoActionPerformed

    private void sieteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sieteMousePressed
        this.uno.setSelected(false);
        this.dos.setSelected(false);
        this.tres.setSelected(false);
        this.cuatro.setSelected(false);
        this.cinco.setSelected(false);
        this.seis.setSelected(false);
        this.siete.setSelected(true);
        this.ocho.setSelected(false);
    }//GEN-LAST:event_sieteMousePressed

    private void sieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sieteActionPerformed
        CtrlUsuarios ctrl = new CtrlUsuarios();
        if(ctrl.validarUsuarioModulo(txtId.getText(), "6")){
            pnlUsuarios usu = new pnlUsuarios();        
            ConsultaUsuarios mod = new ConsultaUsuarios();
            new CambiaPanel(pnlPrincipal, usu);
            new CambiaPanel(pnlBarraMenu, new paneles.menu_usuarios(usu));
            if(this.siete.isSelected()){
                this.uno.setColorNormal(new Color(239,238,244));
                this.uno.setColorHover(new Color(204,204,204));
                this.uno.setColorPressed(new Color(204,204,204));

                this.dos.setColorNormal(new Color(239,238,244));
                this.dos.setColorHover(new Color(204,204,204));
                this.dos.setColorPressed(new Color(204,204,204));

                this.tres.setColorNormal(new Color(239,238,244));
                this.tres.setColorHover(new Color(204,204,204));
                this.tres.setColorPressed(new Color(204,204,204));

                this.cuatro.setColorNormal(new Color(239,238,244));
                this.cuatro.setColorHover(new Color(204,204,204));
                this.cuatro.setColorPressed(new Color(204,204,204));
                
                this.cinco.setColorNormal(new Color(239,238,244));
                this.cinco.setColorHover(new Color(204,204,204));
                this.cinco.setColorPressed(new Color(204,204,204));

                this.seis.setColorNormal(new Color(239,238,244));
                this.seis.setColorHover(new Color(204,204,204));
                this.seis.setColorPressed(new Color(204,204,204));

                this.siete.setColorNormal(new Color(204,204,204));
                this.siete.setColorHover(new Color(204,204,204));
                this.siete.setColorPressed(new Color(204,204,204));

                this.ocho.setColorNormal(new Color(239,238,244));
                this.ocho.setColorHover(new Color(204,204,204));
                this.ocho.setColorPressed(new Color(204,204,204));
            }else{
                this.siete.setColorNormal(new Color(239,238,244));
                this.siete.setColorHover(new Color(204,204,204));
                this.siete.setColorPressed(new Color(204,204,204));
            }
        }else {
            JOptionPane.showMessageDialog(null, "No tiene permisos para acceder a \neste módulo");
        }
    }//GEN-LAST:event_sieteActionPerformed

    private void seisMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seisMousePressed
        this.uno.setSelected(false);
        this.dos.setSelected(false);
        this.tres.setSelected(false);
        this.cuatro.setSelected(false);
        this.cinco.setSelected(false);
        this.seis.setSelected(true);
        this.siete.setSelected(false);
        this.ocho.setSelected(false);
    }//GEN-LAST:event_seisMousePressed

    private void seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seisActionPerformed
        CtrlUsuarios ctrl = new CtrlUsuarios();
        if(ctrl.validarUsuarioModulo(txtId.getText(), "5")){
            pnlListaTecnicos tec = new pnlListaTecnicos();
            ConsultaEmpleados mod = new ConsultaEmpleados(); 
            new CambiaPanel(pnlPrincipal, tec);
            new CambiaPanel(pnlBarraMenu, new paneles.menu_tecnicos(tec));
            
            if(this.seis.isSelected()){
                this.uno.setColorNormal(new Color(239,238,244));
                this.uno.setColorHover(new Color(204,204,204));
                this.uno.setColorPressed(new Color(204,204,204));

                this.dos.setColorNormal(new Color(239,238,244));
                this.dos.setColorHover(new Color(204,204,204));
                this.dos.setColorPressed(new Color(204,204,204));

                this.tres.setColorNormal(new Color(239,238,244));
                this.tres.setColorHover(new Color(204,204,204));
                this.tres.setColorPressed(new Color(204,204,204));

                this.cuatro.setColorNormal(new Color(239,238,244));
                this.cuatro.setColorHover(new Color(204,204,204));
                this.cuatro.setColorPressed(new Color(204,204,204));
                
                this.cinco.setColorNormal(new Color(239,238,244));
                this.cinco.setColorHover(new Color(204,204,204));
                this.cinco.setColorPressed(new Color(204,204,204));

                this.seis.setColorNormal(new Color(204,204,204));
                this.seis.setColorHover(new Color(204,204,204));
                this.seis.setColorPressed(new Color(204,204,204));

                this.siete.setColorNormal(new Color(239,238,244));
                this.siete.setColorHover(new Color(204,204,204));
                this.siete.setColorPressed(new Color(204,204,204));

                this.ocho.setColorNormal(new Color(239,238,244));
                this.ocho.setColorHover(new Color(204,204,204));
                this.ocho.setColorPressed(new Color(204,204,204));
            }else{
                this.seis.setColorNormal(new Color(239,238,244));
                this.seis.setColorHover(new Color(204,204,204));
                this.seis.setColorPressed(new Color(204,204,204));
            }
        }else {
            JOptionPane.showMessageDialog(null, "No tiene permisos para acceder a \neste módulo");
        }
    }//GEN-LAST:event_seisActionPerformed

    private void cincoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cincoMousePressed
        this.uno.setSelected(false);
        this.dos.setSelected(false);
        this.tres.setSelected(false);
        this.cuatro.setSelected(false);
        this.cinco.setSelected(true);
        this.seis.setSelected(false);
        this.siete.setSelected(false);
        this.ocho.setSelected(false);
    }//GEN-LAST:event_cincoMousePressed

    private void cincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cincoActionPerformed
        CtrlUsuarios ctrl = new CtrlUsuarios();
        if(ctrl.validarUsuarioModulo(txtId.getText(), "4")){
            String id_usuario = txtId.getText();
            pnlAutorizacion auto = new pnlAutorizacion(id_usuario);
            new CambiaPanel(pnlPrincipal, auto);
            new CambiaPanel(pnlBarraMenu, new paneles.pnlMenuVacio());
            
            if(this.cinco.isSelected()){
                this.uno.setColorNormal(new Color(239,238,244));
                this.uno.setColorHover(new Color(204,204,204));
                this.uno.setColorPressed(new Color(204,204,204));

                this.dos.setColorNormal(new Color(239,238,244));
                this.dos.setColorHover(new Color(204,204,204));
                this.dos.setColorPressed(new Color(204,204,204));

                this.tres.setColorNormal(new Color(239,238,244));
                this.tres.setColorHover(new Color(204,204,204));
                this.tres.setColorPressed(new Color(204,204,204));

                this.cuatro.setColorNormal(new Color(239,238,244));
                this.cuatro.setColorHover(new Color(204,204,204));
                this.cuatro.setColorPressed(new Color(204,204,204));
                
                this.cinco.setColorNormal(new Color(204,204,204));
                this.cinco.setColorHover(new Color(204,204,204));
                this.cinco.setColorPressed(new Color(204,204,204));
                
                this.seis.setColorNormal(new Color(239,238,244));
                this.seis.setColorHover(new Color(204,204,204));
                this.seis.setColorPressed(new Color(204,204,204));

                this.siete.setColorNormal(new Color(239,238,244));
                this.siete.setColorHover(new Color(204,204,204));
                this.siete.setColorPressed(new Color(204,204,204));

                this.ocho.setColorNormal(new Color(239,238,244));
                this.ocho.setColorHover(new Color(204,204,204));
                this.ocho.setColorPressed(new Color(204,204,204));
            }else{
                this.cinco.setColorNormal(new Color(239,238,244));
                this.cinco.setColorHover(new Color(204,204,204));
                this.cinco.setColorPressed(new Color(204,204,204));
            }
        }else {
            JOptionPane.showMessageDialog(null, "No tiene permisos para acceder a \neste módulo");
        }
    }//GEN-LAST:event_cincoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cerrar();
    }//GEN-LAST:event_formWindowClosing

    private void nueveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nueveMousePressed
        // TODO add your handling code here:
        this.uno.setSelected(false);
        this.dos.setSelected(false);
        this.tres.setSelected(false);
//        this.cuatro.setSelected(false);
        this.cinco.setSelected(false);
        this.seis.setSelected(false);
        this.siete.setSelected(false);
        this.ocho.setSelected(true);
    }//GEN-LAST:event_nueveMousePressed

    private void nueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nueveActionPerformed
        // TODO add your handling code here:
        CtrlUsuarios ctrl = new CtrlUsuarios();
        if(ctrl.validarUsuarioModulo(txtId.getText(), "7")){
            Caja_menor cbl = new Caja_menor();
            new CambiaPanel(pnlPrincipal, cbl);        
            new CambiaPanel(pnlBarraMenu, new paneles.pnlMenuVacio());
            //CtrlMunicipios ctrl = new CtrlMunicipios();
            if(this.nueve.isSelected()){
                this.uno.setColorNormal(new Color(239,238,244));
                this.uno.setColorHover(new Color(204,204,204));
                this.uno.setColorPressed(new Color(204,204,204));

                this.dos.setColorNormal(new Color(239,238,244));
                this.dos.setColorHover(new Color(204,204,204));
                this.dos.setColorPressed(new Color(204,204,204));

                this.tres.setColorNormal(new Color(239,238,244));
                this.tres.setColorHover(new Color(204,204,204));
                this.tres.setColorPressed(new Color(204,204,204));

                this.cuatro.setColorNormal(new Color(239,238,244));
                this.cuatro.setColorHover(new Color(204,204,204));
                this.cuatro.setColorPressed(new Color(204,204,204));
                
                this.cinco.setColorNormal(new Color(239,238,244));
                this.cinco.setColorHover(new Color(204,204,204));
                this.cinco.setColorPressed(new Color(204,204,204));

                this.seis.setColorNormal(new Color(239,238,244));
                this.seis.setColorHover(new Color(204,204,204));
                this.seis.setColorPressed(new Color(204,204,204));

                this.siete.setColorNormal(new Color(239,238,244));
                this.siete.setColorHover(new Color(204,204,204));
                this.siete.setColorPressed(new Color(204,204,204));

                this.ocho.setColorNormal(new Color(204,204,204));
                this.ocho.setColorHover(new Color(204,204,204));
                this.ocho.setColorPressed(new Color(204,204,204));
            }else{
                this.ocho.setColorNormal(new Color(239,238,244));
                this.ocho.setColorHover(new Color(204,204,204));
                this.ocho.setColorPressed(new Color(204,204,204));
            }
        }else {
            JOptionPane.showMessageDialog(null, "No tiene permisos para acceder a \neste módulo");
        }                               
    }//GEN-LAST:event_nueveActionPerformed

    private void lblUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarioMouseClicked
        diaEditUser dialog = new diaEditUser(new java.awt.Frame(), true, txtId.getText());
        dialog.setVisible(true);
    }//GEN-LAST:event_lblUsuarioMouseClicked

   
    
 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    new Principal().setVisible(true);
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    public void cerrar(){
        Object [] opciones ={"Aceptar","Cancelar"};

        JOptionPane mensaje = new JOptionPane();

        int eleccion = JOptionPane.showOptionDialog(this,
        "¿Desea salir del sistema?",
        "Sistemas Palacios Ltda",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE,
        null,
        opciones,
        "Aceptar");        
        switch(eleccion){
            case JOptionPane.YES_OPTION:
                System.exit(0);
            break;
            case JOptionPane.NO_OPTION:   
                
            break;        
        }
        
      }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro cinco;
    private rsbuttom.RSButtonMetro cuatro;
    private rsbuttom.RSButtonMetro dos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblUsuario;
    private rsbuttom.RSButtonMetro nueve;
    private rsbuttom.RSButtonMetro ocho;
    private javax.swing.JPanel pnlBarraMenu;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlPrincipal;
    private rsbuttom.RSButtonMetro seis;
    private rsbuttom.RSButtonMetro siete;
    private rsbuttom.RSButtonMetro tres;
    private javax.swing.JTextField txtId;
    private rsbuttom.RSButtonMetro uno;
    // End of variables declaration//GEN-END:variables


    
    //Contabilidad
           
}
