/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package paneles;

import Controlador.CtrlViaticos;
import Modelo.ConsultaViaticos;
import static paneles.menu_tecnicos.setJPanelMenuBar;
import principal.diaEntregaViaticos;
import java.awt.BorderLayout;
import javax.swing.JMenuBar;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRootPane;
import principal.diaViaticosMun;

/**
 *
 * @author AUXINVTIC
 */
public class menu_viaticos extends javax.swing.JPanel {

    String usuario;
    public menu_viaticos(String id_usuario) {
        initComponents();
        setJPanelMenuBar(this, child, menubar);
        this.usuario = id_usuario;
    }
    
    public static void setJPanelMenuBar(JPanel parent, JPanel child, JMenuBar menuBar) {
        parent.removeAll();
        parent.setLayout(new BorderLayout());
        JRootPane root = new JRootPane();
        parent.add(root, BorderLayout.CENTER);
        root.setJMenuBar(menuBar);
        root.getContentPane().add(child);
        parent.putClientProperty("root", root);  //if you need later
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menubar = new javax.swing.JMenuBar();
        entregaViaticos = new javax.swing.JMenu();
        entregaViaticosMun = new javax.swing.JMenu();
        child = new javax.swing.JPanel();

        menubar.setBackground(new java.awt.Color(255, 255, 255));
        menubar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 0, 0), null));
        menubar.setAlignmentX(1.5F);
        menubar.setBorderPainted(false);
        menubar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        entregaViaticos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        entregaViaticos.setText("Entrega de viáticos Pasto");
        entregaViaticos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        entregaViaticos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entregaViaticosMouseClicked(evt);
            }
        });
        menubar.add(entregaViaticos);

        entregaViaticosMun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        entregaViaticosMun.setText("Entrega de viáticos Municipios");
        entregaViaticosMun.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        entregaViaticosMun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entregaViaticosMunMouseClicked(evt);
            }
        });
        menubar.add(entregaViaticosMun);

        child.setLayout(new javax.swing.BoxLayout(child, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(child, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(child, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void entregaViaticosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entregaViaticosMouseClicked
        
        diaEntregaViaticos dialog = new diaEntregaViaticos(new java.awt.Frame(), true, this.usuario);
        ConsultaViaticos mod = new ConsultaViaticos();
        CtrlViaticos control = new CtrlViaticos(dialog, mod);
        
        dialog.setVisible(true);
    }//GEN-LAST:event_entregaViaticosMouseClicked

    private void entregaViaticosMunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entregaViaticosMunMouseClicked
        diaViaticosMun dialog = new diaViaticosMun(new java.awt.Frame(), true, this.usuario);
        dialog.setVisible(true);
    }//GEN-LAST:event_entregaViaticosMunMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel child;
    private javax.swing.JMenu entregaViaticos;
    private javax.swing.JMenu entregaViaticosMun;
    private javax.swing.JMenuBar menubar;
    // End of variables declaration//GEN-END:variables

}
