/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;


import Controlador.CtrlTecnicos;
import Modelo.ConsultaEmpleados;
import principal.Principal;
import principal.diaRegEmpleado;
import java.awt.BorderLayout;
import javax.swing.JDialog;
import javax.swing.JMenuBar;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRootPane;

/**
 *
 * @author AUXINVTIC
 */
public class menu_tecnicos extends javax.swing.JPanel {
    
    pnlListaTecnicos pnl;  
    
    public menu_tecnicos(pnlListaTecnicos pnl) {
        initComponents();
        setJPanelMenuBar(this, child, menubar);
        this.pnl = pnl;
        
    }
    
    public static void setJPanelMenuBar(JPanel parent, JPanel child, JMenuBar menuBar) {
        parent.removeAll();
        parent.setLayout(new BorderLayout());
        JRootPane root = new JRootPane();
        parent.add(root, BorderLayout.CENTER);
        root.setJMenuBar(menuBar);
        root.getContentPane().add(child);
        parent.putClientProperty("root", root);  //if you need later
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menubar = new javax.swing.JMenuBar();
        regTecnicos = new javax.swing.JMenu();
        child = new javax.swing.JPanel();

        menubar.setBackground(new java.awt.Color(255, 255, 255));
        menubar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 0, 0), null));
        menubar.setAlignmentX(1.5F);
        menubar.setBorderPainted(false);
        menubar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        regTecnicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        regTecnicos.setText("Registrar empleado");
        regTecnicos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        regTecnicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regTecnicosMouseClicked(evt);
            }
        });
        menubar.add(regTecnicos);

        child.setLayout(new javax.swing.BoxLayout(child, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(child, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(child, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void regTecnicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regTecnicosMouseClicked
        //JOptionPane.showMessageDialog(null, "Ingrese el número de identificación del técnico", "Importante", JOptionPane.ERROR_MESSAGE);
        //pnlRegTecnicos tecn = new pnlRegTecnicos();
        //new paneles.CambiaPanel(reg, new Paneles.pnlTecnicos());
        
        diaRegEmpleado dialog = new diaRegEmpleado(new java.awt.Frame(), true, this.pnl);
        dialog.setVisible(true);
    }//GEN-LAST:event_regTecnicosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel child;
    private javax.swing.JMenuBar menubar;
    private javax.swing.JMenu regTecnicos;
    // End of variables declaration//GEN-END:variables
}
