/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import Controlador.CtrlReportes;
import Modelo.Empleado;
import Modelo.Mes;
import Modelo.TipoDoc;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LinearGradientPaint;
import java.awt.RenderingHints;
import java.awt.Stroke;
import java.awt.geom.Point2D;
import java.awt.geom.RoundRectangle2D;
import java.io.File;
import java.util.StringTokenizer;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicProgressBarUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author AUXINVTIC
 */
public class pnlReportes extends javax.swing.JPanel {

    CtrlReportes ctrl = new CtrlReportes();
    JFileChooser selecArchivo = new JFileChooser();
    File archivo ;
    int contAccion = 0;
    public pnlReportes() {
        initComponents();
        agregarEstilos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnExportar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        lblEmpleado = new javax.swing.JLabel();
        cbTipoReporte = new javax.swing.JComboBox<>();
        cbEmpleado = new javax.swing.JComboBox<>();
        fechaInicial = new com.toedter.calendar.JDateChooser();
        fechaFinal = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReporte = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Panel de información a consultar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(51, 51, 51))); // NOI18N
        jPanel4.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Fecha inicial:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Reporte:");

        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(102, 102, 102));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnExportar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnExportar.setForeground(new java.awt.Color(102, 102, 102));
        btnExportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/csv.png"))); // NOI18N
        btnExportar.setText("Exportar");
        btnExportar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExportar.setIconTextGap(6);
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(102, 102, 102));
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/broom.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        lblEmpleado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEmpleado.setForeground(new java.awt.Color(51, 51, 51));
        lblEmpleado.setText("Empleado:");

        cbTipoReporte.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbTipoReporte.setForeground(new java.awt.Color(51, 51, 51));
        cbTipoReporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbTipoReporte.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTipoReporteItemStateChanged(evt);
            }
        });
        cbTipoReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoReporteActionPerformed(evt);
            }
        });

        cbEmpleado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbEmpleado.setForeground(new java.awt.Color(51, 51, 51));
        cbEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        fechaInicial.setDateFormatString("d-MM-yyyy");
        fechaInicial.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        fechaFinal.setDateFormatString("d-MM-yyyy");
        fechaFinal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Fecha final:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                        .addGap(32, 32, 32))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(fechaInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(13, 13, 13)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                        .addGap(34, 34, 34))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(fechaFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(8, 8, 8)))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(31, 31, 31))
                    .addComponent(cbTipoReporte, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(cbEmpleado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExportar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(430, 430, 430))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblEmpleado)
                                    .addComponent(jLabel2))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbTipoReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(fechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBuscar)
                            .addComponent(btnLimpiar)
                            .addComponent(btnExportar))
                        .addGap(3, 3, 3)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        tblReporte.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblReporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblReporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblReporte.setGridColor(new java.awt.Color(204, 204, 204));
        tblReporte.setRowHeight(25);
        tblReporte.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tblReporte.setSelectionForeground(new java.awt.Color(204, 51, 0));
        tblReporte.setShowVerticalLines(false);
        tblReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblReporteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblReporte);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Total:");

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(51, 51, 51));
        lblTotal.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotal)
                .addGap(169, 169, 169))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblTotal))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        TipoDoc tipo = (TipoDoc) cbTipoReporte.getSelectedItem();
        Empleado empleado = (Empleado) cbEmpleado.getSelectedItem();
        
        if(fechaInicial.getDate() == null){
            JOptionPane.showMessageDialog(null, "Ingrese una fecha inicial.");
        }if(fechaFinal.getDate() == null){
            JOptionPane.showMessageDialog(null, "Ingrese una fecha final.");
        }else if(tipo.getIdTipoDoc().equals("0")){
            JOptionPane.showMessageDialog(null, "Seleccione un tipo de reporte");
        }else{
            if(tipo.getIdTipoDoc().equals("1")){
                ctrl.consultarReporteGeneral(this, 1);
            }
            if(tipo.getIdTipoDoc().equals("3")){
                ctrl.consultarReporteGeneral(this, 3);
            }
            if(tipo.getIdTipoDoc().equals("2")){
                if(empleado.getId().equals("0")){
                    JOptionPane.showMessageDialog(null, "Seleccione un empleado");
                }else{
                    ctrl.consultaReporteEmpleado(this);
                }                
            }
        }        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        TipoDoc tipo = (TipoDoc) cbTipoReporte.getSelectedItem();
        Empleado empleado = (Empleado) cbEmpleado.getSelectedItem();
        int b = 0;
        if(fechaInicial.getDate() == null){
            JOptionPane.showMessageDialog(null, "Ingrese una fecha inicial.");
        }if(fechaFinal.getDate() == null){
            JOptionPane.showMessageDialog(null, "Ingrese una fecha final.");
        }else if(tipo.getIdTipoDoc().equals("0")){
            JOptionPane.showMessageDialog(null, "Seleccione un tipo de reporte");
        }else{
            if(tipo.getIdTipoDoc().equals("1")){
                b = 1;
                validarReporte(b);
            }
            if(tipo.getIdTipoDoc().equals("3")){
                b = 2;
                validarReporte(b);
            }
            if(tipo.getIdTipoDoc().equals("2")){
                if(empleado.getId().equals("0")){
                    JOptionPane.showMessageDialog(null, "Seleccione un empleado");
                }else{
                    validarReporte(b);
                }                
            }
        }
        
        
    }//GEN-LAST:event_btnExportarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void cbTipoReporteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTipoReporteItemStateChanged
        TipoDoc tipodoc = (TipoDoc) cbTipoReporte.getSelectedItem();
        if(tipodoc.getIdTipoDoc().equals("0")){
            cbEmpleado.setVisible(false);
            lblEmpleado.setVisible(false);
        }
        if(tipodoc.getIdTipoDoc().equals("1")){
            cbEmpleado.setVisible(false);
            lblEmpleado.setVisible(false);
        }
        if(tipodoc.getIdTipoDoc().equals("2")){
            cbEmpleado.setVisible(true);
            lblEmpleado.setVisible(true);
        }
        if(tipodoc.getIdTipoDoc().equals("3")){
            cbEmpleado.setVisible(false);
            lblEmpleado.setVisible(false);
        }
    }//GEN-LAST:event_cbTipoReporteItemStateChanged

    private void tblReporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblReporteMouseClicked
        int fila = tblReporte.rowAtPoint(evt.getPoint());
        int columna = tblReporte.columnAtPoint(evt.getPoint());
        
        if(columna == 12){
            //JOptionPane.showMessageDialog(null,"Bien");
            validarSeleccion(fila);
        }
    }//GEN-LAST:event_tblReporteMouseClicked

    private void cbTipoReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoReporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoReporteActionPerformed

    private void validarSeleccion(int fila) {
       String obs = tblReporte.getValueAt(fila, 14).toString();
       String just = tblReporte.getValueAt(fila, 15).toString();
       
       if(obs == null){
           obs = "";
       }
       if(just == null){
           just = "";
       }
       StringTokenizer cant = new StringTokenizer(just, " ");
       String obsver = organizarFrase(obs);
       String justver = organizarFrase(just);       
       if(obs == "" && cant.countTokens() == 0){
           JOptionPane.showMessageDialog(null, "No tiene observaciones");           
       }else{
           JOptionPane.showMessageDialog(null, obsver +"\n"+justver);
       }
        
    }
    public String organizarFrase(String cadena){
        String words[] = cadena.split(" ");
        int numPal = words.length;
        String cad = "";
        int c = 4;
        if(numPal > 0){
           for(int i = 0; i<numPal; i++){
               if(i == c){
                   cad += words[i]+"\n ";
                   c += 4;
               }else{
                   cad += words[i]+" ";
               }
           }
        }
       return cad;
    }
    
    public void agregarEstilos(){
        ctrl.llenarComboBox(cbTipoReporte);
        ctrl.listarEmpleados(cbEmpleado);
        cbEmpleado.setVisible(false);
        lblEmpleado.setVisible(false);        
        
    }

    
    public void limpiar(){
        fechaInicial.setDate(null);
        fechaFinal.setDate(null);
        cbTipoReporte.setSelectedIndex(0);
        DefaultTableModel modelo = (DefaultTableModel) tblReporte.getModel();
        while(modelo.getRowCount()>0)modelo.removeRow(0);
    }
    
    public void validarReporte(int b){ 
        if(b == 1){
            if(selecArchivo.showDialog(null, "Exportar") == JFileChooser.APPROVE_OPTION){
                archivo = selecArchivo.getSelectedFile();
                archivo = new File(archivo.toString()+".csv");
                ctrl.exportarReporteGeneral(this, archivo, 1); 
            }
        }else if(b == 2){
            if(selecArchivo.showDialog(null, "Exportar") == JFileChooser.APPROVE_OPTION){
                archivo = selecArchivo.getSelectedFile();
                archivo = new File(archivo.toString()+".csv");
                ctrl.exportarReporteGeneral(this, archivo, 2); 
            }
        }else{
            if(selecArchivo.showDialog(null, "Exportar") == JFileChooser.APPROVE_OPTION){
                archivo = selecArchivo.getSelectedFile();
                archivo = new File(archivo.toString()+".csv");
                ctrl.exportarReporteEmpleado(this, archivo);
            }
        }        
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnLimpiar;
    public javax.swing.JComboBox<String> cbEmpleado;
    public javax.swing.JComboBox<String> cbTipoReporte;
    public com.toedter.calendar.JDateChooser fechaFinal;
    public com.toedter.calendar.JDateChooser fechaInicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEmpleado;
    public javax.swing.JLabel lblTotal;
    public javax.swing.JTable tblReporte;
    // End of variables declaration//GEN-END:variables
}
