/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import Controlador.CtrlAutorizacion;
import Modelo.Autorizacion;
import Modelo.Dependencia;
import dialogs.diaEditAutorizacion;
import javax.swing.JOptionPane;

/**
 *
 * @author AUXINVTIC
 */
public class pnlAutorizacion extends javax.swing.JPanel {

    CtrlAutorizacion ctrl = new CtrlAutorizacion();
    public pnlAutorizacion(String id_usuario) {
        initComponents();
        ctrl.llenarDependencias(cbDependencia);
        ctrl.llenarTablaAutorizaciones(tablaAutorizacion);
        txtJustificacion.setLineWrap(true);
        txtJustificacion.setWrapStyleWord(true);
        txtUsuario.setText(id_usuario);
        txtUsuario.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        cbDependencia = new javax.swing.JComboBox<>();
        cbEmpleado = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtJustificacion = new javax.swing.JTextArea();
        btnSaveViatico = new javax.swing.JButton();
        btnClean = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaAutorizacion = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Autorizaciones al personal", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(102, 102, 102))); // NOI18N

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("Seleccione un empleado:");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setText("Seleccione una dependencia:");

        cbDependencia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbDependencia.setForeground(new java.awt.Color(51, 51, 51));
        cbDependencia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbDependencia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbDependenciaItemStateChanged(evt);
            }
        });

        cbEmpleado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbEmpleado.setForeground(new java.awt.Color(51, 51, 51));
        cbEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setText("Valor a autorizar:");

        txtValor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setText("Justificación:");

        txtJustificacion.setColumns(20);
        txtJustificacion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtJustificacion.setRows(5);
        txtJustificacion.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtJustificacion.setSelectionColor(new java.awt.Color(204, 0, 0));
        jScrollPane1.setViewportView(txtJustificacion);

        btnSaveViatico.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSaveViatico.setForeground(new java.awt.Color(102, 102, 102));
        btnSaveViatico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/diskette.png"))); // NOI18N
        btnSaveViatico.setText("Guardar");
        btnSaveViatico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSaveViatico.setIconTextGap(6);
        btnSaveViatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveViaticoActionPerformed(evt);
            }
        });

        btnClean.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnClean.setForeground(new java.awt.Color(102, 102, 102));
        btnClean.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/broom.png"))); // NOI18N
        btnClean.setText("Limpiar");
        btnClean.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClean.setIconTextGap(6);
        btnClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanActionPerformed(evt);
            }
        });

        tablaAutorizacion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tablaAutorizacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaAutorizacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tablaAutorizacion.setGridColor(new java.awt.Color(204, 204, 204));
        tablaAutorizacion.setRowHeight(30);
        tablaAutorizacion.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tablaAutorizacion.setSelectionForeground(new java.awt.Color(204, 51, 0));
        tablaAutorizacion.setShowVerticalLines(false);
        tablaAutorizacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaAutorizacionMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaAutorizacion);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Autorizaciones registradas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel26)
                                    .addComponent(cbDependencia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbEmpleado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtValor)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSaveViatico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClean)
                        .addGap(39, 39, 39)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE))
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(27, 27, 27))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbDependencia, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveViatico)
                    .addComponent(btnClean))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(46, 46, 46))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveViaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveViaticoActionPerformed
        ctrl.registrarAutorizacion(this);
    }//GEN-LAST:event_btnSaveViaticoActionPerformed

    private void btnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanActionPerformed
        limpiar();
    }//GEN-LAST:event_btnCleanActionPerformed

    private void cbDependenciaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbDependenciaItemStateChanged
        Dependencia dep = (Dependencia) cbDependencia.getSelectedItem();
        ctrl.llenarCargos(cbEmpleado, dep.getId_dependencia());
    }//GEN-LAST:event_cbDependenciaItemStateChanged

    private void tablaAutorizacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaAutorizacionMouseClicked
        int fila = tablaAutorizacion.rowAtPoint(evt.getPoint());
        int columna = tablaAutorizacion.columnAtPoint(evt.getPoint());
        
        if(columna == 5){
            //JOptionPane.showMessageDialog(null,"Bien");
            validarSeleccionEditar(fila);
        }
        if(columna == 6){
            //JOptionPane.showMessageDialog(null,"Bien");
            ctrl.validarSeleccionAnular(fila, this);
        }
    }//GEN-LAST:event_tablaAutorizacionMouseClicked

    private void limpiar(){
        cbDependencia.setSelectedIndex(0);
        txtValor.setText("");
        txtJustificacion.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnSaveViatico;
    public javax.swing.JComboBox<String> cbDependencia;
    public javax.swing.JComboBox<String> cbEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable tablaAutorizacion;
    public javax.swing.JTextArea txtJustificacion;
    public javax.swing.JTextField txtUsuario;
    public javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables

    private void validarSeleccionEditar(int fila) {
        Autorizacion auto = new Autorizacion();
        auto.setId_autorizacion(tablaAutorizacion.getValueAt(fila, 0).toString());
        auto.setJustificacion(tablaAutorizacion.getValueAt(fila, 3).toString());
        auto.setValor(tablaAutorizacion.getValueAt(fila, 4).toString());
        diaEditAutorizacion dialog = new diaEditAutorizacion(new java.awt.Frame(), true, auto, this); 
        dialog.setVisible(true);
    }
    
}
