
package paneles;

import Controlador.CtrlAjustes;
import Controlador.CtrlMunicipios;
import Modelo.Peaje;
import dialogs.diaBackup;
import dialogs.diaMunicipios;
import dialogs.diaNewCargos;
import dialogs.diaNewDependencia;
import dialogs.diaOtrosViaticos;
import dialogs.diaParqueaderos;
import dialogs.diaPeajes;
import dialogs.diaTransporte;
import principal.diaEditPeaje;


public class pnlSettings extends javax.swing.JPanel {

    /**
     * Creates new form pnlHome
     */
    public pnlSettings() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlDependencias = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnlPeajes = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pnlParqueaderos = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pnlTransporte = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pnlMunicipios = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        pnlCargos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnlBackups = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pnlOtros = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlDependencias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlDependencias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlDependenciasMouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/office.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel1.setBackground(new java.awt.Color(204, 51, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dependencias");
        jLabel1.setOpaque(true);

        javax.swing.GroupLayout pnlDependenciasLayout = new javax.swing.GroupLayout(pnlDependencias);
        pnlDependencias.setLayout(pnlDependenciasLayout);
        pnlDependenciasLayout.setHorizontalGroup(
            pnlDependenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDependenciasLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(23, 23, 23))
        );
        pnlDependenciasLayout.setVerticalGroup(
            pnlDependenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDependenciasLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(17, 17, 17))
        );

        jPanel1.add(pnlDependencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 40, 180, 190));

        pnlPeajes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlPeajes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlPeajesMouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/toll.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel7.setBackground(new java.awt.Color(204, 51, 0));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Peajes");
        jLabel7.setOpaque(true);

        javax.swing.GroupLayout pnlPeajesLayout = new javax.swing.GroupLayout(pnlPeajes);
        pnlPeajes.setLayout(pnlPeajesLayout);
        pnlPeajesLayout.setHorizontalGroup(
            pnlPeajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPeajesLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(23, 23, 23))
        );
        pnlPeajesLayout.setVerticalGroup(
            pnlPeajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPeajesLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(17, 17, 17))
        );

        jPanel1.add(pnlPeajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 180, 190));

        pnlParqueaderos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlParqueaderos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlParqueaderosMouseClicked(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/parq.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel9.setBackground(new java.awt.Color(204, 51, 0));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Parqueaderos");
        jLabel9.setOpaque(true);

        javax.swing.GroupLayout pnlParqueaderosLayout = new javax.swing.GroupLayout(pnlParqueaderos);
        pnlParqueaderos.setLayout(pnlParqueaderosLayout);
        pnlParqueaderosLayout.setHorizontalGroup(
            pnlParqueaderosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlParqueaderosLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(23, 23, 23))
        );
        pnlParqueaderosLayout.setVerticalGroup(
            pnlParqueaderosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlParqueaderosLayout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(17, 17, 17))
        );

        jPanel1.add(pnlParqueaderos, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 180, 190));

        pnlTransporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlTransporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlTransporteMouseClicked(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bus.png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel11.setBackground(new java.awt.Color(204, 51, 0));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Transporte");
        jLabel11.setOpaque(true);

        javax.swing.GroupLayout pnlTransporteLayout = new javax.swing.GroupLayout(pnlTransporte);
        pnlTransporte.setLayout(pnlTransporteLayout);
        pnlTransporteLayout.setHorizontalGroup(
            pnlTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTransporteLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(23, 23, 23))
        );
        pnlTransporteLayout.setVerticalGroup(
            pnlTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTransporteLayout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(17, 17, 17))
        );

        jPanel1.add(pnlTransporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 180, 190));

        pnlMunicipios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlMunicipios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMunicipiosMouseClicked(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/location.png"))); // NOI18N
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel13.setBackground(new java.awt.Color(204, 51, 0));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Municipios");
        jLabel13.setOpaque(true);

        javax.swing.GroupLayout pnlMunicipiosLayout = new javax.swing.GroupLayout(pnlMunicipios);
        pnlMunicipios.setLayout(pnlMunicipiosLayout);
        pnlMunicipiosLayout.setHorizontalGroup(
            pnlMunicipiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMunicipiosLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(23, 23, 23))
        );
        pnlMunicipiosLayout.setVerticalGroup(
            pnlMunicipiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMunicipiosLayout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addGap(17, 17, 17))
        );

        jPanel1.add(pnlMunicipios, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, 180, 190));

        pnlCargos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlCargos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlCargosMouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/group.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel4.setBackground(new java.awt.Color(204, 51, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Cargos");
        jLabel4.setOpaque(true);

        javax.swing.GroupLayout pnlCargosLayout = new javax.swing.GroupLayout(pnlCargos);
        pnlCargos.setLayout(pnlCargosLayout);
        pnlCargosLayout.setHorizontalGroup(
            pnlCargosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCargosLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(23, 23, 23))
        );
        pnlCargosLayout.setVerticalGroup(
            pnlCargosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCargosLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(17, 17, 17))
        );

        jPanel1.add(pnlCargos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 180, 190));

        pnlBackups.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlBackups.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlBackupsMouseClicked(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/database_1.png"))); // NOI18N
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel15.setBackground(new java.awt.Color(204, 51, 0));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Copias de seguridad");
        jLabel15.setOpaque(true);

        javax.swing.GroupLayout pnlBackupsLayout = new javax.swing.GroupLayout(pnlBackups);
        pnlBackups.setLayout(pnlBackupsLayout);
        pnlBackupsLayout.setHorizontalGroup(
            pnlBackupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackupsLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(23, 23, 23))
        );
        pnlBackupsLayout.setVerticalGroup(
            pnlBackupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackupsLayout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addGap(17, 17, 17))
        );

        jPanel1.add(pnlBackups, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 180, 190));

        pnlOtros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlOtros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlOtrosMouseClicked(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sheet.png"))); // NOI18N
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel17.setBackground(new java.awt.Color(204, 51, 0));
        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Otros viáticos");
        jLabel17.setOpaque(true);

        javax.swing.GroupLayout pnlOtrosLayout = new javax.swing.GroupLayout(pnlOtros);
        pnlOtros.setLayout(pnlOtrosLayout);
        pnlOtrosLayout.setHorizontalGroup(
            pnlOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOtrosLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(23, 23, 23))
        );
        pnlOtrosLayout.setVerticalGroup(
            pnlOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOtrosLayout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addGap(17, 17, 17))
        );

        jPanel1.add(pnlOtros, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 180, 190));

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void pnlDependenciasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDependenciasMouseClicked
        CtrlAjustes ctrl = new CtrlAjustes();
        diaNewDependencia dialog = new diaNewDependencia(new java.awt.Frame(), true);
        ctrl.llenarTabla(dialog.tablaDependencias);
        dialog.setVisible(true);
    }//GEN-LAST:event_pnlDependenciasMouseClicked

    private void pnlCargosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCargosMouseClicked
        CtrlAjustes ctrl = new CtrlAjustes();
        diaNewCargos dialog = new diaNewCargos(new java.awt.Frame(), true);
        ctrl.llenarTablaCargos(dialog.tablaCargos);
        ctrl.llenarDependencias(dialog.cbDependencia);
        dialog.setVisible(true);
    }//GEN-LAST:event_pnlCargosMouseClicked

    private void pnlMunicipiosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMunicipiosMouseClicked
        CtrlMunicipios ctrl = new CtrlMunicipios();
        diaMunicipios dialog = new diaMunicipios(new java.awt.Frame(), true); 
        ctrl.listarMunicipios(dialog.tablaMunicipios);        
        dialog.setVisible(true);
    }//GEN-LAST:event_pnlMunicipiosMouseClicked

    private void pnlPeajesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPeajesMouseClicked
        CtrlMunicipios ctrl = new CtrlMunicipios();
        diaPeajes dialog = new diaPeajes(new java.awt.Frame(), true); 
        ctrl.listarPeajes(dialog.tablaPeajes);        
        dialog.setVisible(true);
    }//GEN-LAST:event_pnlPeajesMouseClicked

    private void pnlParqueaderosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlParqueaderosMouseClicked
        CtrlMunicipios ctrl = new CtrlMunicipios();
        diaParqueaderos dialog = new diaParqueaderos(new java.awt.Frame(), true); 
        ctrl.listarParqueaderos(dialog.tablaParqueaderos);        
        dialog.setVisible(true);
    }//GEN-LAST:event_pnlParqueaderosMouseClicked

    private void pnlTransporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTransporteMouseClicked
        CtrlMunicipios ctrl = new CtrlMunicipios();
        diaTransporte dialog = new diaTransporte(new java.awt.Frame(), true); 
        ctrl.listarGasolina(dialog.tablaTransporte);        
        dialog.setVisible(true);
    }//GEN-LAST:event_pnlTransporteMouseClicked

    private void pnlBackupsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBackupsMouseClicked
        diaBackup dialog = new diaBackup(new java.awt.Frame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_pnlBackupsMouseClicked

    private void pnlOtrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlOtrosMouseClicked
        CtrlMunicipios ctrl = new CtrlMunicipios();
        diaOtrosViaticos dialog = new diaOtrosViaticos(new java.awt.Frame(), true); 
        ctrl.listarOtrosViaticos(dialog.tablaOtrosViaticos);        
        dialog.setVisible(true);
    }//GEN-LAST:event_pnlOtrosMouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlBackups;
    private javax.swing.JPanel pnlCargos;
    private javax.swing.JPanel pnlDependencias;
    private javax.swing.JPanel pnlMunicipios;
    private javax.swing.JPanel pnlOtros;
    private javax.swing.JPanel pnlParqueaderos;
    private javax.swing.JPanel pnlPeajes;
    private javax.swing.JPanel pnlTransporte;
    // End of variables declaration//GEN-END:variables
}
