/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import Controlador.CtrlAutorizacion;
import Controlador.CtrlViaticos;
import Modelo.Dependencia;
import Modelo.Empleado;
import Modelo.Viatico;
import dialogs.diaDevolucionViatico;
import java.awt.Color;
import java.awt.Font;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AUXINVTIC
 */
public class pnlViatico extends javax.swing.JPanel {

    CtrlViaticos ctrl = new CtrlViaticos();
    public pnlViatico() {
        initComponents();
        ctrl.llenarDependencias(cbDependencias);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        cbDependencias = new javax.swing.JComboBox<>();
        lblEmpleado = new javax.swing.JLabel();
        cbEmpleado = new javax.swing.JComboBox<>();
        txtFecha = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDevoluciones = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro de devoluciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(51, 51, 51))); // NOI18N
        jPanel4.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Dependencia:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Empleado:");

        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(102, 102, 102));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(102, 102, 102));
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/broom.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        cbDependencias.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbDependencias.setForeground(new java.awt.Color(51, 51, 51));
        cbDependencias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbDependencias.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbDependenciasItemStateChanged(evt);
            }
        });

        lblEmpleado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEmpleado.setForeground(new java.awt.Color(51, 51, 51));
        lblEmpleado.setText("Fecha:");

        cbEmpleado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbEmpleado.setForeground(new java.awt.Color(51, 51, 51));
        cbEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbEmpleado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbEmpleadoItemStateChanged(evt);
            }
        });

        txtFecha.setDateFormatString("dd-MM-yyyy");
        txtFecha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(16, 16, 16))
                    .addComponent(cbDependencias, 0, 120, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(cbEmpleado, 0, 120, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(74, 74, 74)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                        .addGap(70, 70, 70)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar)
                        .addGap(61, 61, 61))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblEmpleado)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(lblEmpleado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbDependencias, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(btnLimpiar)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblDevoluciones.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblDevoluciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblDevoluciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblDevoluciones.setGridColor(new java.awt.Color(204, 204, 204));
        tblDevoluciones.setRowHeight(30);
        tblDevoluciones.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tblDevoluciones.setSelectionForeground(new java.awt.Color(204, 51, 0));
        tblDevoluciones.setShowVerticalLines(false);
        tblDevoluciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDevolucionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDevoluciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(237, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        Empleado emp = (Empleado) cbEmpleado.getSelectedItem();
        Dependencia dep = (Dependencia) cbDependencias.getSelectedItem();
                
        if(dep.getId_dependencia().equals("0")){
            JOptionPane.showMessageDialog(null, "Seleccione una dependencia");
        }else if(emp.getId().equals("0")){
            JOptionPane.showMessageDialog(null, "Seleccione un empleado");
        }else if(txtFecha.getDate() == null){
            JOptionPane.showMessageDialog(null, "Ingrese una fecha");
        }else{
            Date fecha = txtFecha.getDate();        
            String strDateFormat = "yyyy-MM-dd"; // El formato de fecha está especificado  
            SimpleDateFormat f = new SimpleDateFormat(strDateFormat);        
            String fecha_ingresada = f.format(fecha);
            ctrl.listarViaticosEntregados(tblDevoluciones, emp.getId(), fecha_ingresada);
        }
        
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void cbEmpleadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbEmpleadoItemStateChanged
        
    }//GEN-LAST:event_cbEmpleadoItemStateChanged

    private void cbDependenciasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbDependenciasItemStateChanged
        Dependencia dep = (Dependencia) cbDependencias.getSelectedItem();
        CtrlAutorizacion ctrlAuto = new CtrlAutorizacion();
        ctrlAuto.llenarCargos(cbEmpleado, dep.getId_dependencia());
    }//GEN-LAST:event_cbDependenciasItemStateChanged

    private void tblDevolucionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDevolucionesMouseClicked
        int fila = tblDevoluciones.rowAtPoint(evt.getPoint());
        int columna = tblDevoluciones.columnAtPoint(evt.getPoint());                
        if(columna == 7){
            validarSeleccionPeaje(fila);
        }
    }//GEN-LAST:event_tblDevolucionesMouseClicked

    private void validarSeleccionPeaje(int fila) {
        String valor = ctrl.verificarRegistroDevolucion(tblDevoluciones.getValueAt(fila, 8).toString());
        if(valor != null){
            JOptionPane.showMessageDialog(null, "El item seleccionado ya tiene registrado \nuna devolución por el valor de $"+valor);
        }else{            
            Empleado emp = (Empleado) cbEmpleado.getSelectedItem();
            Date fecha = txtFecha.getDate();        
            String strDateFormat = "yyyy-MM-dd"; // El formato de fecha está especificado  
            SimpleDateFormat f = new SimpleDateFormat(strDateFormat);        
            String fecha_ingresada = f.format(fecha);
            Viatico viatico = new Viatico();
            viatico.setId_viatico(Integer.parseInt(tblDevoluciones.getValueAt(fila, 8).toString()));
            viatico.setFechaSalida(tblDevoluciones.getValueAt(fila, 3).toString());
            viatico.setFechaRegreso(tblDevoluciones.getValueAt(fila, 4).toString());
            viatico.setValor(Integer.parseInt(tblDevoluciones.getValueAt(fila, 6).toString()));
            viatico.setFechaProgramada(fecha_ingresada);
            viatico.setId_tecnico(emp.getId());

            diaDevolucionViatico dialog = new diaDevolucionViatico(new java.awt.Frame(), true, viatico, this); 
            dialog.setVisible(true);
        }
    }
    
    public void limpiar(){
        cbDependencias.setSelectedIndex(0);
        txtFecha.setDate(null);
        DefaultTableModel modelo = (DefaultTableModel) tblDevoluciones.getModel();
        while(modelo.getRowCount()>0)modelo.removeRow(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnLimpiar;
    public javax.swing.JComboBox<String> cbDependencias;
    public javax.swing.JComboBox<String> cbEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEmpleado;
    public javax.swing.JTable tblDevoluciones;
    public com.toedter.calendar.JDateChooser txtFecha;
    // End of variables declaration//GEN-END:variables
}
